extends Node

const SPEED_LERP_COEF = 0.25
const TILE_SIZE = 64
const EPS = 1e-5

const MIN_VELOCITY = 1
const MIN_VELOCITY_SQUARED = MIN_VELOCITY * MIN_VELOCITY

const MAX_CASTING_LEVEL = 10
const CASTING_LEVEL_DEFAULT = 5
const CASTING_LEVEL_MOVE = 3


const HIT_HIGHLIGHT_TIME = 0.75
